DROP DATABASE IF EXISTS saskatchewanizon;
CREATE DATABASE saskatchewanizon;
USE saskatchewanizon;

CREATE TABLE categories (
  categoryId INT NOT NULL PRIMARY KEY,
  category VARCHAR(255)
);

CREATE TABLE itemData (
  productId INT NOT NULL PRIMARY KEY,
  productName VARCHAR(255),
  productDescription TEXT,
  price FLOAT,
  categoryId INT,
  imgUrl VARCHAR(255),
  rating FLOAT DEFAULT 5,
  prime BOOLEAN,
  FOREIGN KEY (categoryId) REFERENCES categories(categoryId)
);

INSERT INTO categories 
  (categoryId, category) 
VALUES 
  (1, 'Hockey'),
  (2, 'Syrup'),
  (3, 'Music'),
  (4, 'Camping'),
  (5, 'Hunting'),
  (6, 'Food');

INSERT INTO itemData 
  (productId, productName, productDescription, price, categoryId, imgUrl, rating, prime) 
VALUES 
  (1, 'STX Ice Hockey Surgeon RX3 Hockey Stick', 'HPR - with an ultra-high balance point and performance engineering the high performance ratio of the new stallion stick has been optimized for players seeking durability and performance all in one', 74.32, 1, 'https://images-na.ssl-images-amazon.com/images/I/515Pu1JIHoL._SL1000_.jpg', DEFAULT, FALSE),
  (2, 'Shock Doctor Pro Mouth Guard', 'Our sports mouth guard is suitable for all contact sports where a mouth guard is required or recommended like: football, basketball, lacrosse, hockey, MMA, boxing, jiu jitsu and much more', 5.69, 1, 'https://images-na.ssl-images-amazon.com/images/I/710TCPdOn1L._SL1500_.jpg', DEFAULT, FALSE),
  (3, 'American Ice Force 2.0 Hockey Skate', 'Perfect skates for beginner skaters to intermediate skaters. Indoor and Outdoor skates, good for pond hockey. Light-weight sidewall injection mold giving the skate a custom fit right out of the box.', 39.99, 1 , 'https://images-na.ssl-images-amazon.com/images/I/81LOj56WfRL._SL1500_.jpg', 2.8, FALSE),
  (4, 'Franklin Sports Youth Hockey Goalie Masks - GFM1500', 'These youth goalie masks are designed specifically for street hockey. Quick-snap elastic straps are designed for an adjustable fit to keep the mask tight and comfortable for all goalies. Constructed from high-impact plastic with a welded steel cage, this mask is designed to be durable and safe', 45.99, DEFAULT, 'https://images-na.ssl-images-amazon.com/images/I/81BgUHAnI9L._SL1500_.jpg', 2, FALSE),
  (5, 'Faswin 12 Pack Classic Ice Hockey Puck', 'Case of 12 Black Official Hockey Pucks with 2 Reusable Mesh Bag Regulation Size and Weight, Pond Hockey or On the Rink, VulcanizedRubber. Remarkable flatness, hardness and smooth surface quality for consistent, powerful and accurate shots and passes.', 17.88, 1, 'https://images-na.ssl-images-amazon.com/images/I/618XId%2BwOiL._SL1500_.jpg', DEFAULT, FALSE),
  (6, 'STIGA NHL Stanley Cup Hockey Game, Tabletop Size, 96-cm x 50-cm x 10-cm', 'High-quality table hockey game with official NHL team colors and logos. Expertly crafted 3D players outfitted in Maple Leaf and Red Wing uniforms Easy-to-move control rods; behind-the-net plexi-shield protectors. Puck ejectors in each goal; goalies move from side to side', 139.59, DEFAULT, 'https://images-na.ssl-images-amazon.com/images/I/41KMpDrcYGL.jpg', 3, FALSE),
  (7, 'Franklin Sports Street Hockey Goal - Steel Street Hockey Net - All Weather Durable Outdoor Goal - 54"', 'HEAVY DUTY: This street hockey goal is built with 1" diameter steel tubing designed to last season after season. PRO STYLE: The goal is designed with pro-style top shelf and back support brace so you can let it rip just like the pros! DURABLE NETTING: This goal features ultra heavyweight netting so it can stand up to even the hardest slapshots', 42.87, DEFAULT, 'https://images-na.ssl-images-amazon.com/images/I/81aT8Fto2jL._SL1500_.jpg', 3.5, FALSE),
  (8, 'PLAYMOBIL NHL Boston Bruins Goalie', 'Be Boston Strong with the NHL Boston Bruins Goalie! Connect the figure to the goal in the NHL Hockey Arena for added fun! Figures can bend, sit, stand and turn their heads. Includes one goalie figure with Bruins jersey, hockey stick, player number decals, face mask, and other protective gear', 13.99, 1, 'https://images-na.ssl-images-amazon.com/images/I/41-Dk3DK%2BfL.jpg', DEFAULT, FALSE),
  (9, 'Stanley Cup', 'The Stanley Cup is the championship trophy awarded annually to the National Hockey League (NHL) playoff winner. It is the oldest existing trophy to be awarded to a professional sports franchise in North America, and the International Ice Hockey Federation (IIHF) considers it to be one of the most important championships available to the sport.', 0.60, 1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Stanley_Cup%2C_2015.jpg/320px-Stanley_Cup%2C_2015.jpg', DEFAULT, FALSE),
  (10, 'Boston Bruins David Pastrňák Authentic Pro Jersey Black', '- Polyester - Authentic team crest - Mesh insert under arms - Officially licensed by the NHL - Climalite fabric sweeps sweat away from your skin - Authentic tie-down fight strap with hook-and-loop and snap closure', 189.90, 1, 'https://images-na.ssl-images-amazon.com/images/I/71n5zLuj04L._SL1500_.jpg', DEFAULT, FALSE),
  (11, 'Detroit Red Wings Coverall Infant Baby ', 'Button snaps on back and bottom of creeper 55% Cotton/45% Polyester Long Sleeve Attached footies Machine wash Officially licensed Imported Brand: Outerstuff', 19.97, 1, 'https://images-na.ssl-images-amazon.com/images/I/61dIbIbidrL._SL1000_.jpg', DEFAULT, FALSE),
  (12, 'StoreYourBoard Hockey Stick Rack', 'Durable Hockey Stick Rack. Holds up to 15 Hockey Sticks. Hang your ice hockey skates, helmet, and gloves from the rack, too. Great way to organize your home and garage.', 19.99, 1, 'https://images-na.ssl-images-amazon.com/images/I/81M8n3wWYQL._SL1500_.jpg', DEFAULT, FALSE),
  (13, '50 Strong BPA Free Water Bottle', 'Our customizable designs include basketball, softball, soccer, football, tennis, baseball and more. Great for Christmas, thank you, team bottles, and back to school presents. Perfect for girls, boys, tweens, teens, and adults.', 15.99, 1, 'https://images-na.ssl-images-amazon.com/images/I/71Pvudp4SML._SL1500_.jpg', DEFAULT, FALSE),
  (14, 'Franklin Sports Hockey Shooting Target - NHL - Fits 54 x 44 Inch Hockey Goal - Perfect For Hockey Shooting Practice - 5 Targets', '- FITS GOAL SIZE: 54" (w) x 44" (h). Goal not included - EASY SET UP: Adjustable self-stick straps for easy attachment to any 54" goal - WATERPROOF: Rugged 210D waterproof construction - USE WITH OFFICIAL STREET HOCKEY BALL: Designed for use with official 2 5/8" street hockey ball only - NHL APPROVED: Dynamic full-size goalie graphic image with 5 clearly defined shooting target holes- ', 14.32, 1, 'https://images-na.ssl-images-amazon.com/images/I/81QWN3%2B0lTL._SL1500_.jpg', DEFAULT, FALSE),
  (15, '400 Card NHL Hockey Gift Set - w/ Superstars, Hall of Fame Players', '- Any hockey collector will enjoy the variety. - Cards will span the last 30+ years! - Includes Four Hard Plastic cases perfecting for stacking and protecting the cards - 400 Assorted Hockey Cards. - Includes star cards, hall-of-famers, and other assorted cards', 23.23, 1, 'https://images-na.ssl-images-amazon.com/images/I/51IQTrt5ykL.jpg', DEFAULT, FALSE),
  (16, 'Bauer Vapor Pro Carry Hockey Bag', 'Details Pro Tarp HD Webbing Reinforcement HD Waterproof Tarpaulin bottom D-Shape opening of main compartment Skate Pocket, Organizer Panel, Internal glove mesh pocket Dryout panel and dry flow grommets Rivet reinforced HD Dual Layer webbing', 79.00, 1, 'https://images-na.ssl-images-amazon.com/images/I/51GR-ygi2NL._SL1000_.jpg', DEFAULT, FALSE),
  (17, 'Charlie Conway #96 Mighty Ducks Adam Banks #99 Movie Ice Hockey Jersey Green White', '- 100% High Quality Polyester - Breathable Mesh Fabric - Sleeveless Quick Dry Jersey - Embroidery and Double Stitched Name, Number and logo - Available Colors: As seen in Pictures. Available Sizes: S-XXXL', 29.88, 1, 'https://images-na.ssl-images-amazon.com/images/I/91eDv0FGC4L._UX679_.jpg', DEFAULT, FALSE),
  (18, 'Maple Leaf Syrup Nips, Set Of 4 Bottles', "Whether you're a native Canadian or simply a syrup fan, these leaf-shaped bottles will make you smile. They're adorable. Best of all, they are filled the world's best, most delicious maple syrup—from Canada of course. Our medium amber grade A maple syrup is certified the best Canada has to offer, and Canada has grading standards stricter than any other country. Called nips because of their diminutive size, these 1.7 oz. leaf-shaped bottles are perfect for party and wedding favors, gifts or travel...really, the list goes on and on. Grade A medium amber maple syrup: sweet, robust flavorCute (and collectible!) 1.7 oz. bottles shaped like maple leavesSet of 4 bottlesMade in the USA", 19.80, 2, 'https://www.vermontcountrystore.com/ccstore/v1/images/?source=/file/v1915755195306600286/products/H4826.main.png&height=700&width=450&outputFormat=JPEG&quality=0.8', 3.1, FALSE),
  (19, 'ILA Maple Leaf Syrup', 'Wood-fired Vermont Maple syrup made the old-fashioned way: boiled down over pruned maple branches. Harvested in Vermont. Usage: For cooking and baking as well as table syrup. Ila, meaning earth, beauty and prayer in Sanskrit, is a Brooklyn based brand offering a collection of essential ingredients for your kitchen and home.  Each product is carefully sourced from farms, purveyors and artisans around the world.', 30, 2, 'https://cdn.shopify.com/s/files/1/0246/1503/products/IMG_5436_1024x1024.jpg?v=1575586792', DEFAULT, FALSE),
  (20, 'Pure New York Maple Syrup in Log Cabin Bottle', 'PURE NEW YORK MAPLE SYRUP!! Pure maple syrup made from tapping maple trees in NY. Boiled down from its watery form (sap) into a more condensed maple flavored syrup. It takes about 44 gallons of sap to make one gallon of maple syrup. Great for pouring over pancakes, waffles, ice cream, yogurt and many other foods! Amazing maple flavor and taste. Either medium or light amber Vermont grade syrup. 250ml bottle For large quantity orders email me so we can work something out.', 9.00, 2, 'https://i.etsystatic.com/14956240/r/il/9ddfc5/1177980494/il_1588xN.1177980494_jauz.jpg', DEFAULT, FALSE),
  (21, 'Maple Syrup Hard Candy, 1 Pound Bag', "These amber translucent leaf candies are made with pure maple syrup and 'glow' when held up to the light. They're shaped like petite maple leaves and melt away slowly, leaving behind the sweet flavor of real maple syrup. Made with pure maple syrup Melt-in-your-mouth delicious. Maple hard candies in the shape of a maple leaf. Enjoy on their own or drop one on your favorite cup of tea for a comforting sweet treat. Each hard candy is individually wrapped 1 lb. bag", 16.95, 2, 'https://www.vermontcountrystore.com/ccstore/v1/images/?source=/file/v1308369356246302349/products/33917.main.png&height=700&width=450&outputFormat=JPEG&quality=0.8', DEFAULT, FALSE),
  (22, 'Pure, Organic Canadian Maple Syrup, All-Natural, Grade-A Amber Rich Taste | Deli', "Naturally Delicious - This Grade-A Amber Rich Taste maple syrup is perfect for pancakes, waffles, desserts, drinks and all your favorite sweet treats with a smooth, natural flavor. Pure, Organic Quality - A family owned-and-operated brand, our Canadian organic maple syrup is free of additives, preservatives and artificial flavors. Vegan Friendly - Kosher and organic syrup is completely naturally and totally delicious, making it great for kids, adults and special dietary needs. Resealable Freshness Unlike most Canadian maple syrup brands, our glass bottles can be resealed tight to ensure a fresh, sweet taste every time it's opened. Canadian Made Quality - Every bottle of our organic pure maple syrup is crafted in Canada to ensure you get the best maple syrup available.", 36.95, 2, 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS_Jbeywxx9qUBhJobfq0hLUuoVatidGjPVkqVHzNQ2hqftm8oog7HS2QmRmQH4vvUA_KN1UHge0lo_7Bpoko0iicV_AbwloXL5wjkyzdmhWcKgCjoPrde1f7ms&usqp=CAY' , 2.8, FALSE),
  (23, "Runamok Maple Maple Syrup, Sugarmaker's Cut - 375 ml", "Sugarmaker's Cut - it is all in the name; the very best organic maple syrup of the season; it's special. The sugarmaker's cut maple syrup is the syrup that is set aside because the flavor is at the peak. So image your favorite maple syrup and then better. A Amber colored maple syrup with a truly divine and rich taste - Grade A. This is the syrup the Runamok Maple Team's flagship. Try it on your pancakes, but don't stop there, use it in many more of your recipes, like baking, soup, salad, meat etc", 17.50, 2, 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSY0YUdAAoOQMMw-eKBcLL-XmZq-eDr4C5K8vEQAgmXOH8jtlGP0LLIBGqtcA3luT8icAfzd1WkrZ7DGyShSstJuCw2V8mXqDWsg0EfuPlAWuA38zY3NQrwiw&usqp=CAY', DEFAULT, FALSE),
  (24, 'Award Winning Escuminac Canadian Maple Syrup - Gift Bundle - Easter Gift - Grade A - Extra Rare, Great Harvest and Late Harvest - Pure Organic Unblended Single Forest - 3 X 1.7 fl oz (50 ml)', "Discover our three exquisite gourmet grade A Canadian maple syrup flavours! This bundle is comprised of our #1 selling velvety Extra Rare, intensely dark and robust Late Harvest, our rich and refined amber Great Harvest Canadian maple syrups. 100% Pure Unblended Canadian maple syrup. 100% traceable from forest to plate (Single Forest). Michelin Guide's TOP RATED 3 STAR AWARD for 2015. Gluten free and vegan, 100% certified USDA Organic, Canada Organic NO additives, NO preservatives, NO artificial flavours. An absolute unforgettable taste! Brilliantly designed modern glass bottles (see images, DEFAULT, FALSE), these are NOT your typical beige maple syrup plastic jugs... A great gift idea for friends and family. Give the gift of maple syrup for birthdays, anniversaries, weddings, Valentine's day and Christmas. Grade a maple syrup from Quebec, Canada. Great as a pancake syrup, on desserts and in drinks.", 74.62, 2, 'https://images-na.ssl-images-amazon.com/images/I/41CmCsw9jRL.jpg', DEFAULT, FALSE),
  (25, 'Crown Maple® Bourbon Barrel Aged Maple Syrup Gallon (3.79 L) - Glass', 'Distinctive aromas and flavors of bourbon, smoky oak, graham cracker, brown butter & creamy vanilla are showcased in Crown Maple Bourbon Barrel Aged organic maple syrup which presents exceptional layers of luxurious flavors. First, certified organic, pure maple syrup is aged in barrels to absorb the flavor of bourbon from the oak. Then, we bottled it at our state-of-the-art sugarhouse in Dover Plains, in New York’s Hudson Valley. The elegant packaging of this unique syrup is designed to reflect the superb quality of the product within, described in The Wall Street Journal as “soul-stirring”.', 115.00, 2, 'https://cdn11.bigcommerce.com/s-ec3t5d56yg/images/stencil/1280x1280/products/207/866/CrownMaple_BourbonGallon600x600__44363.1528143025.jpg?c=2&imbypass=on', DEFAULT, FALSE),
  (26, 'Digital Maple Syrup Grader', "Grade with confidence knowing your results are reported objectively according to industry standards with your Maple Syrup Digital Grader. With a digital read out, there is no more no guesswork on the grade of your maple syrup. Simple to use and our digital grader's compact design fits in your pocket. Easier to use and more accurate than a visual maple syrup grading kit. It only takes one button and a few seconds to grade your maple syrup. Great for maple syrup producers and packers.", 59.00, 2,'https://cdn11.bigcommerce.com/s-l8qlnhq2eh/products/5869/images/6514/hi759-_2___57285.1559321285.1280.1280.jpg?c=2', DEFAULT, FALSE),
  (27, 'Pure Maple Syrup, Canada No 1 Medium,can 540ml Made in Canada', '100% PURE MALE SYRUP NO FAT SOURCE OF IRON AND CALCIUM PURE MAPLE SYRUP MADE IN CANADA IN THE COLD WINTER.', 23.92, 2, 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSmltUZTZJRPFndponqJUnCn8cNoBs6cUhWoMtklK1Ixp98O-_UPwfaG8_6525gjbFZg5aEHn3wZxXJpiSvslYNMjDkxcsbXQ&usqp=CAY', DEFAULT, FALSE),
  (28, 'Round Glass Replacement Cuvettes for HI759 Maple Syrup Digital Grader (25 pcs)', 'The HI731359 are the replacement glass cuvettes used with the HI759 Maple Syrup Digital Grader. The Digital Grader measures the transmittance of light through a glycerol reference standard and compares it to a syrup sample. For the meter to accurately do this, proper cuvettes must be used to ensure there is no interference from scratches or inconsistencies in the glass. The HI731359 is a kit that contains 25 round glass cuvettes along with 25 sturdy plastic inserts. This kit is not only ideal for sizeable sugar houses who grade multiple samples per day, but also for those who wish to store graded samples throughout the season. Optically clear glass 10 mL level mark for adding correct volume Durable plastic inserts for storage', 25.00, 2, 'https://cdn11.bigcommerce.com/s-l8qlnhq2eh/products/5163/images/7212/hi731359_1__15755.1559321299.220.290.jpg?c=2', DEFAULT, FALSE),
  (29, 'Tap My Trees 2145 Maple Sugaring Spile And Hook, Stainless Steel', 'Screw / Nail · Metal Used in the maple sugaring process. Fits 7/16 inch tap hole in tree. Hook is attached to spile and used to hang the sap bucket. Spile is inserted into drilled hole to transfer sap into the bucket. Bucket lid attaches to spile by inserting lid rod through hole on side of spile. - Material: Stainless Steel, Type: Spile & Hook, Pkg Qty: 1.', 3.59, 2, 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQT2N3OxNvvqhJojKMddZvAKaDn5QXI1OFenhgXTH-WvdxkDrtQrmNbKiZBjtT7DZjYOIcMrAfhDQh6cG_skuGZJnze9qFCashjOa4D1HsGSd977BnZxV-V&usqp=CAY', DEFAULT, FALSE),
  (30, 'Maple Syrup Pairing Gift Set (2-Pack)', 'How sweet it is. Don’t tell pancakes but...maple syrup makes the perfect addition to a mixed drink. This easy-to-gift set includes ginger root, hibiscus, jasmine tea, and smoked pecan wood flavors in stunningly labeled glass bottles that’ll look right at home atop a bar cart. Each set is hand-picked (and taste-tasted) from the very best trees in Northern Vermont. Just think of all the cocktail possibilities! Each pairing set is infused with unique flavors: Cocktail Pairing Set: Jasmine Tea, Smoked with Pecan Wood, Ginger Root, Hibiscus Flower  Ice Cream Pairing Set: Cinnamon, Hibiscus Flower, Whiskey Barrel-Aged, Rum Barrel-Aged Cheese Pairing Set: Elderberry, Smoked with Pecan Wood, Hibiscus Flower, Bourbon Barrel-Aged', 52.00, 2, 'https://images.food52.com/13IJOzbCSaNfY9Rm7WNt5krGjhE=/2000x0/a02a2420-f328-432e-b159-19400475aced--2019-0510_runamok_vermont-maple-syrup-pairing-gift-sets-2-pack_1x1_james-ransom_322.jpg', DEFAULT, FALSE),
  (31, 'Pure Maple Syrup Jug Ornament', 'Most associate maple syrup with pancakes, but in recent years maple syrup has begun to replace white cane sugar as a sweetener. Legend has it that the first maple syrup use was a happenstance discovery as a result of Chief Woksis, an Iroquois Indian throwing his tomahawk at a tree, after he retrieved it the next morning to go out hunting his wife saw the syrup oozing down the tree! Lucky for us she was observant, and so maple sugar use was born! This is a great glass ornament for a food themed tree!', 15.99, 2, 'https://cdn.shopify.com/s/files/1/1531/4421/products/maple-syrup-bottle-ornament-by-old-world-christmas.jpg?v=1511190035', DEFAULT, FALSE),
  (32, 'BOURBON MAPLE SYRUP', "This miniature, wax-sealed bottle is the perfect size for tucking into your bag, so you're pancake-ready wherever you go. Mikuni gets used barrels from Tuthilltown Spirits in the Hudson Valley (New York's first whiskey distillery since Prohibition, DEFAULT, FALSE), and fill 'em up with medium amber grade maple syrup from heritage sugar shacks in Quebec. The syrup takes on layers of wood and smoke from the charred barrels, along with a hint of the bourbon that had been soaked up by the wood.", 5.50, 2, 'https://cdn.shopify.com/s/files/1/0100/5392/products/NobleBourbonMapleSyrup900_900x600_crop_center@2x.progressive.jpg?v=1569894984', DEFAULT, FALSE),
  (33, 'Crown Maple® Amber Color Rich Taste Maple Syrup Gallon (3.79 L) - Glass', 'The aromas and flavors of gingerbread, roasted chestnut, toffee, and a hint of clove and nutmeg, are showcased in Crown Maple Amber Color Rich Taste organic, pure maple syrup which presents a medium-body feel with a depth of luxurious flavors. Sweeten black teas and lightly roasted coffees Glaze pork tenderloin, chicken, and swordfish Use in marinades and sauces for chicken wings Caramelize roasted Brussels sprouts and root vegetables Add complex sweetness to spiced nuts Cocktails with more robust spirits such as a Mint Julep or Maple-tini', 95.00, 2, 'https://cdn11.bigcommerce.com/s-ec3t5d56yg/images/stencil/1280x1280/products/204/863/CrownMaple_AmberGallon600x600__63084.1528142801.jpg?c=2&imbypass=on&imbypass=on', DEFAULT, FALSE),
  (34, 'Crown Maple® Very Dark Color Strong Taste Maple Syrup Gallon (3.79 L) - Plastic', 'Deeply caramelized flavors and aromas of molasses, crème brûleè, espresso, and cocoa beans with hints of clove, allspice, and anise, make Crown Maple Very Dark Color Strong Taste organic, pure maple syrup the most full-bodied syrup in our line.  Complex and packed with flavor, this is our most assertive syrup with the strongest maple impact. Sweeten hot chocolate, black tea & deeply roasted coffee Adds complexity and intrigue to basting glazes, sauces, remoulades, and mustards Ideal for pies such as chocolate pecan and shoofly pie Use in granola & energy bars Add bold flavor to oatmeal, yogurt, grits, cream of wheat, and polenta Ideal for cocktails made with aged and smoky spirits', 90.00, 2, 'https://cdn11.bigcommerce.com/s-ec3t5d56yg/images/stencil/1280x1280/products/261/913/CrownMaple_VeryDarkGallon__71486.1544409029.jpg?c=2&imbypass=on&imbypass=on', DEFAULT, FALSE),
  (36, 'Alanis Morisette', 'Jagged Little Pill - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 14.99, 3, 'https://images-na.ssl-images-amazon.com/images/I/81UsU658UVL._SL1425_.jpg', 3.4, FALSE),
  (37, 'Leonard Cohen', 'You Want It Darker - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 12.95, 3, 'https://img.discogs.com/ZfxkupUTnqAENW6lBmF8Yl64xj4=/fit-in/600x597/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-9466485-1482091537-3185.jpeg.jpg', DEFAULT, FALSE),
  (38, 'Celine Dion', 'The Essential Celine Dion - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 11.99, 3, 'https://img.discogs.com/gFhzNeVo-OhgZ5OyIPOnDC-ORdg=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4437064-1506217697-6403.jpeg.jpg', DEFAULT, FALSE),
  (39, 'Avril Lavigne', 'Avril Lavigne - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 8.99, 3, 'https://img.discogs.com/_YEnwZX0sbrLn94fpF4zad867_Y=/fit-in/600x598/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4124430-1356261154-9307.jpeg.jpg', DEFAULT, FALSE),
  (40, 'Sarah McLachlan', 'Surfacing - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 13.95, 3, 'https://img.discogs.com/-AaK9JJ8EnSTZOjpV7Zk651CO_k=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1058668-1460863624-6948.jpeg.jpg', DEFAULT, FALSE),
  (41, 'Nelly Furtado', 'Whoa, Nelly - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 7.95, 3, 'https://img.discogs.com/4TAGG9klLZC2k0lReuMErdvNDPs=/fit-in/600x594/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2715920-1490751617-9036.jpeg.jpg', DEFAULT, FALSE),
  (42, 'Michelle Branch', 'Hotel Paper - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 11.25, 3, 'https://img.discogs.com/p_vHigdwBDp4uAAJsCDTVJSW9rE=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-573869-1473512744-5093.jpeg.jpg', DEFAULT, FALSE),
  (43, 'Metric', 'Old World Underground - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 14.99, 3, 'https://img.discogs.com/qNFvcvax2z4EsbQXpqKK2mG3pT0=/fit-in/600x525/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-486836-1321098428.jpeg.jpg', DEFAULT, FALSE),
  (44, 'Bif Naked', 'Bif Naked - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 6.99, 3, 'https://img.discogs.com/5IWqqamW5v6xdVCbBRvfaTOu6LE=/fit-in/500x499/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4371877-1412855676-6730.jpeg.jpg', DEFAULT, FALSE),
  (45, 'Drake', 'Thank Me Later - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 7.25, 3, 'https://img.discogs.com/eQ58hdm5i6bMckVaxQl9v-IONVo=/fit-in/467x466/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2564184-1490151172-4422.jpeg.jpg', DEFAULT, FALSE),
  (46, 'Justin Bieber', 'My World - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 1.25, 3, 'https://img.discogs.com/i3BSi5UOQT-z5FI_p-5YhFKH1Ck=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2113771-1264780388.jpeg.jpg', DEFAULT, FALSE),
  (47, 'Joni Mitchell', 'Songs to a Seagull - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 9.99, 3, 'https://img.discogs.com/-9c1oMaw45PMwukNFBD2lkPZMUU=/fit-in/600x599/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1755865-1572106280-8321.jpeg.jpg', DEFAULT, FALSE),
  (48, 'Bryan Adams', 'Bryan Addams - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 9.99, 3, 'https://img.discogs.com/GALRabbQzU4uqQfI9QgFkIqcitY=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1979464-1292309084.jpeg.jpg', DEFAULT, FALSE),
  (49, 'Rufus Wainwright', 'Rufus Wainwright - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 10.75, 3, 'https://img.discogs.com/1YWvbMcPFTRLuHw3L_X1_VNcHS0=/fit-in/497x491/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1160438-1197106026.jpeg.jpg', DEFAULT, FALSE),
  (50, 'Feist', 'Feist - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 12.65, 3, 'https://img.discogs.com/kxPfJdID_sq2S6esBoirV-ONP2w=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/A-19828-1231726265.jpeg.jpg', DEFAULT, FALSE),
  (51, 'Shania Twain', 'Shania Twain - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 11.65, 3, 'https://img.discogs.com/v-Gvq7D2Sjxz9QtYt4rlcBNtkuY=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-429801-1476775497-2961.jpeg.jpg', DEFAULT, FALSE),
  (52, "Le Bon Shoppe Envie Sweater", 'Slightly oversized fit with above the hip hem. Soft and fluffy with no itch. 59% polyester, 29% acrylic, 9% wool, 3% spandex.', 110.00, 4, 'https://static.wixstatic.com/media/63bd66_b7aa0acaa404441982eebecda429e3fd~mv2.png', DEFAULT, FALSE),
  (53, 'axe holster', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://www.canadianoutdoorequipment.com/images/P/cache/damn-yak-axe-holster-620x338.jpg', DEFAULT, FALSE),
  (54, 'beaver', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine. ', 1.00, 4, 'http://cwf-fcf.org/assets/images/CW-JulAug-Beaver.jpg', DEFAULT, FALSE),
  (55, 'pants', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSUvt7NChnjoACHVD1zhiImfhLU-M9RzLbz8p1wXeXBmhqZg0Ja4o5_qp3MzC00p8UdhJQYS3UI&usqp=CAc', DEFAULT, FALSE),
  (56, 'flannel', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://i.pinimg.com/originals/db/43/9a/db439a36b8442214aafef231153351e9.jpg', DEFAULT, FALSE),
  (57, 'belt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://generalleathercraft.com/wp-content/uploads/2018/03/Custom-Canada-Belt.png', DEFAULT, FALSE),
  (58, 'candy', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'http://cdn.shopify.com/s/files/1/0892/1918/products/smores_grande.jpg', DEFAULT, FALSE),
  (59, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://d1w8c6s6gmwlek.cloudfront.net/yournexttshirt.com/products/443/667/4436676.png', DEFAULT, FALSE),
  (60, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'http://ocanadagear.com/graphics/tshirt-ilovecanada1.jpg', DEFAULT, FALSE),
  (61, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://i.ebayimg.com/images/g/1YAAAOSwVYhcBstw/s-l300.jpg', DEFAULT, FALSE),
  (62, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://i.etsystatic.com/5622545/r/il/090b63/1751002904/il_570xN.1751002904_djkv.jpg', DEFAULT, FALSE),
  (63, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://i0.wp.com/shirts-n-giggles.com/wp-content/uploads/2017/10/mockup-6c103f07.jpg', DEFAULT, FALSE),
  (64, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://image.shutterstock.com/image-vector/trust-me-m-canadian-tshirt-600w-1084051736.jpg', DEFAULT, FALSE),
  (65, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://di2ponv0v5otw.cloudfront.net/posts/2019/07/19/5d323eaf29f030572488b960/m_5d323ebaa20dfc782a589db2.jpg', DEFAULT, FALSE),
  (66, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://i.etsystatic.com/20402614/c/1440/1144/0/646/il/a54104/1906641838/il_340x270.1906641838_g05d.jpg', DEFAULT, FALSE),
  (67, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://ak1.ostkcdn.com/images/products/28157125/Mens-Sorry-Definition-Tshirt-Funny-Canada-Apology-Tee-73327532-f59b-4998-8460-0d526877acda_600.jpg', DEFAULT, FALSE),
  (68, 'tshirt', 'carpet in places everyone can see - why hide my amazing artistic clawing skills? brown cats with pink ears hunt anything that moves. My left donut is missing, as is my right why use post when this sofa is here but good morning sunshine.', 1.00, 4,'https://i.etsystatic.com/13007480/r/il/735bf9/1577052982/il_fullxfull.1577052982_juey.jpg', DEFAULT, FALSE),
  (69, 'Primos Hunting 272 Friction Call, Turkey, Starter Pack', 'Double Sided box call sonic dome slate pot. Slim striker sonic dome double with bat. Cut diaphragm mouth call conditioning kit carrying case.A great collection of calls for the beginner or advanced hunter. Includes a Sonic Dome slate call and wooden striker. Includes a Mouth Call and Storage Case', 27.81, 5, 'https://images-na.ssl-images-amazon.com/images/I/81MAl5jhSyL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (70, "Hunter's Specialties Buc-grunter Deer Call", 'Easily produces tending, threatening and reassuring grunts to bring the bucks closer. Flexible ribbed tube channels sound in any direction, producing realistic, deep guttural grunts. Tone can also be changed by cupping hand over the end. Includes instructions and lanyard', 8.46, 5, 'https://images-na.ssl-images-amazon.com/images/I/61o0FyVAQ9L._AC_SL1186_.jpg', DEFAULT, FALSE),
  (71, 'Scent Killer 546-33 Wildlife Research Supercharged Clothing Wash', 'Special unscented formula. No UV brighteners. H-E formula for use in standard machine', 11.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/71NdwF2DOqL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (72, 'Victure Trail Game Camera with Night Vision Motion Activated 1080P 12MP Hunting Cameras with Low Glow and Upgraded Waterproof IP66 for Outdoor Wildlife Watching', '1080P full HD resolution and automatic day/night sensor ensure crisp, vivid images and videos that provide the realistic details you need for in-depth knowledge of game animals‘ behavior characteristics. A trigger speed of 0.5 seconds with 3 continuous shots means you’re less likely to miss capturing an image of wildlife that is quickly moving across the field of view. Victure game camera takes advanced low-glow infrared LED technology and superior motion-activated sensor to produce quality black and white nighttime vision without alerting game. The easy-to-use 2.4 inch LCD screen with user-friendly navigation of image mode options, photo quality, video length, PIR interval, time lapse settings make it simple to customize your scouting specifications. Lower price and higher performance make this trail camera a perfect scouting GIFT for hunting, garden wildlife watching, farm burglar, home security and property surveillance. Using lithium batteries or 6V external power supply will keep it working longer.', 39.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/91WmISYk7EL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (73, 'Leupold RX-850i TBR with DNA Digital Laser Rangefinder, Black/Grey', '100% waterproof and fog proof: absolute waterproof and fog proof integrity – each is ready for a lifetime in the field, in all conditions. 6x magnification gives you plenty of power while maintaining a wide field of view to track game on the move. The durable aluminum housing is shrouded in a rubber armor coating that provides a positive grasp. The RX series rangefinders have a built-in inclinometer with TBR that can calculate the ballistic range to your target, then display it as a holdover aim point, an MOA adjustment, a Milliradian adjustment, or the equivalent horizontal distance. Powered by the readily available CR2 lithium camera battery, the RX-Rangefinders with DNA feature a convenient battery power indicator', 299.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/61SSzO5ng%2BL._SL1001_.jpg', DEFAULT, FALSE),
  (74, 'ATN X-Sight 5-18 Smart Riflescope w/1080p Video, Night Mode, WiFi, GPS, Image Stabilization, IOS and Android Apps', "Wi-Fi, GPS, Geotag, E-Compass, Velocity, Altitude, Record Video/Still images 1080P HD, Day/Night Use. Capable of recording and outputting an image 1080p full HD resolution at 30fps or 720p at 60fps. Unlike traditional optical systems our electronic zoom offers incredible flexibility in the field. Geotagging has never been easier and more seamless; Record and track everywhere you've been and see it on an interactive map. Built-in Wi-Fi allows a user to connect to mobile device or a desktop computer; Use your phone as a viewfinder, upgrade to the latest firmware.Kindly refer the user manual attached below for troubleshooting steps and instructions.", 135.00, 5, 'https://images-na.ssl-images-amazon.com/images/I/41HwtKvz5sL.jpg', DEFAULT, FALSE),
  (75, 'Night Owl Lightweight Night Vision Monocular (4x)', '4x Zoom. Field Of View: 56 Ft @ 200 Ft. 500x Ambient. Light Amplification. 32-ft Dia. & 150-ft Powerful Ir Illumination. Marine night vision monocular with lightweight, water-resistant housing. High-grade, all-glass, camera-quality objective lens with 4x magnification', 227.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/51AUFSIBATL._AC_.jpg', DEFAULT, FALSE),
  (76, 'Mossy Oak Survival Knife, 15-inch Fixed Blade Hunting Bowie Knife with Sharpener and Fire Starter, for Camping, Tactical, Outdoor', 'Overall Length: 15 inch; Blade Length: 10 inch; Thickness: 5/32 inch (3.8 mm); Weight: 16.8 oz. Made of 440C stainless steel for excellent hardness, improved edge retention and rust resistance.Clip Point Blade features saw back, black anodize, ideal for camping expeditions or survival training. Classic designed handle with soft rubber, provides high friction and comfortable non-slip grip for use. Durable heavy duty nylon sheath for easy and safe carry, packaged with a fire starter (black) and a sharpener (sliver). As a perfect camping and hunting knife, it’s suitable for hunter, camper, survivalist or outdoor sports enthusiast so that you can enjoy your adventure', 19.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/61XGNqoQEFL._AC_SL1100_.jpg', DEFAULT, FALSE),
  (77, 'Outdoor Edge SwingBaze Pak, SZP-1, SwingBlaze Double Blade Hunting Knife and Bone Saw Combo with Leather Sheath', 'The ultimate hunting combo set with the rotating SwingBlade knife and T handle wood and bone saw is ideal for quartering big game. SwingBlade knife skinning blade 3.6 inches, gutting blade 3.2 inches, overall length 8.3 inches. Kodi Saw 6 inches long, overall: 9 1/4 inches long. AUS 8 Stainless steel vacuum heat treatment and subzero quenched Rockwell C hardness: 57 to 58. Handles rubberized Kraton, leather sheath', 79.95, 5, 'https://images-na.ssl-images-amazon.com/images/I/41-DcKD%2BxgL._AC_.jpg', DEFAULT, FALSE),
  (78, 'GunSkins Hunting Rifle Skin Camouflage Kit DIY Vinyl Wrap with precut Pieces', 'Made in USA. Fits any Rifle. Easy to install high-performance vinyl. Conforms to any shape. Waterproof non-reflective matte finish. Removable and leaves no residue behind', 64.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/71uBQHGUFlL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (79, 'Bear Archery Salute Ready to Hunt Compound Bow Includes Trophy Ridge Sight, Whisker Biscuit, Peep Sight, and S-Loop', 'Maximum adjustability with a peak draw range of 50 to 70 lbs. and a draw length range of 20 inches to 30 inches. Dual cam system offers a super smooth draw cycle while keeping speed and efficiency. Ready to hunt compound bow comes equipped with Trophy Ridge accessories. 7 ¼ inch brace height offers a high level of forgiveness. Weighs 4 lbs. and shoots up to 300 feet per second.', 189.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/71j0wg8WGcL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (80, "R RUNFUN Men's camo Waterproof Lightweight Hunting Boots", 'Insulated: 400G 3M Thinsulate ultra insulation, along with 600D nylon upper provides extra toughness and warm hunting boot. Breathable & Durable: Anti-Tear 600D Nylon upper material and rubber outsole make the hunting boot resistant to abrasions, tears, and scuffs. Anti-Slip: Self-cleaning ribbed outsole wraps perimeter for maximum stability and performance in mud and snow，protective rubber exteriors resist punctures while providing ample flexibility. Lightweight and Comfortable: The Tidewe hunting boots apply a highly durable and light 600D nylon design instead of the commonly seen rubber shell. Tread comfortably and hunt confidently through the most aggressive terrain.', 99.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/81IUe11w9rL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (81, 'Staghorn Mens All Over Camo Long-Sleeve Tee Shirt', "FINALLY...A CAMO TEE AT A VALUE. Most camo at this price point sticks to your skin, doesn't breathe like you need it, and then shrinks in the dryer. High-quality camo doesn't need to cost a fortune. Introducing: Staghorn Camo. STAY COMFORTABLE: The light stretch of the cotton and polyester blend will have you telling your friends how great your tee fits. Whether you are wearing this whitetail hunting, around the house, or to the store you can be sure you will get compliments. CREATED BY HUNTERS FOR HUNTERS: The tee was made to easily transition from the outdoors to every-day life. We wanted to provide you with a tee that isn't limited to one area of your life. Feel free to lounge or go hunt in the tee as you see fit. IT'S MORE THAN A CAMO PATTERN. It's who you are. Break-Up Country offers incredible effectiveness in all types of terrain where deer reside. DRAMATICALLY LARGER LIMBS, leaves, bark, and branches annihilate your outline at any distance, anywhere in the country.", 13.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/81cN2G-oW6L._AC_UX679_.jpg', DEFAULT, FALSE),
  (82, 'Mossy Oak Cotton Mill 2.0 Camo Hunting Pants for Men Camouflage Clothes', "Men's camo cargo hunting pants made from soft, quiet, and durable. Features two-way stretch all over for extra comfort and mobility, and a crotch gusset for non-binding action fit when sitting, kneeling, or walking. Partial elastic waist for added comfort, button closure with zipper fly, hook and loop tape adjustable waist straps, belt loops, and drawstring ankle cuffs. 6 pockets total: two cargo, two back, & two front. Articulated stitched knees for easier squatting and kneeling. Standard 32” inseam for all sizes. Available in Mossy Oak Break-Up Country, Bottomland, Obsession, Mountain Country, Vintage Greenleaf, Original Bottomland, and Original Treestand.", 39.99, 5, 'https://m.media-amazon.com/images/I/71FRh9H3ZfL._AC_UL320_ML3_.jpg', DEFAULT, FALSE),
  (83, 'Eamber Camouflage Hunting Gloves Full Finger/Fingerless Gloves Pro Anti-Slip Camo Realtree Glove Archery Accessories Hunting Outdoors (M) (L) (L)', '330gsm soft high performance insulating HEAT FLEECE fabric will keep your hands warm,Insulating layer retains warmth. Highly water resistant to keep your hands dry, HYDROSHIELD waterproof membrane specifically engineered to combat the element. Realtree Xtra camouflage print. Added palm protection for better grip and superior durability. Touchscreen compatibility, can wear gloves to touch your phone. This winter waterproof glove includes a neoprene storm guard to block the elements with a Velcro adjustable wrist strap for a comfortable fit.', 10.88, 5, 'https://images-na.ssl-images-amazon.com/images/I/61ytN3oQbjL._AC_SL1000_.jpg', DEFAULT, FALSE),
  (84, 'HaoFst Ghillie Suit Camo Woodland Camouflage Forest Hunting 4-Piece + Bag', 'FULL AND DENSE GHILLIE SUIT:More thread means high density,We minimize the shedding that occurs on all ghillie suits by double stitching the thread. Other ghillie suits use a single stitch to hold the thread on. By double stitching the thread it locks them in so that they will not fall off easily.The Ultimate Lightweight 3D Camouflage concealment. GHILLIE SUIT,HIGH QUALITY—100% Polyester Lining and 100% Polypropylene Strings. Material: Made from tough and durable polyester. Synthetic thread is , Water-repellent, Fire-retardant, Mildew proof, Rot proof. DIMENSION DETAILS—Adult Medium/Large fits chest sizes 40-48 inches and waist sizes 30-48 inches.The cuff and ankle are built with elasticized strap, hood and trouser with adjustable drawstring tie. MANY APPLICATIONS—Hunting, Shooting, Wildfowling, Stalking, Paintball, Airsoft, Surveillance, Wildlife Photography, Birdwatching and even Halloween.HaoFst GHILLIE SUIT is great for all situations where you need deep camouflage. WHAT YOU’ll GET and 100% SATISFACTION GUARANTEE—Package includes:1x Hood with adjustable chin strap and netted face opening.1x Jacket with elastic waist and cuff and snap closures.1x Pants with elastic drawstring waist.1x Gun cover.1x Carry bag with 2 compression straps to compact the suit. HaoFst GHILLIE SUIT comes with100% Satisfaction Guarantee and is dedicated to address any product & service issues and committed to delivering a 5 star experience for all your customers.', 99.99, 5, 'https://images-na.ssl-images-amazon.com/images/I/81bi3Ace1HL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (85, 'Work Sharp Guided Field Sharpener', 'COMPLETE KNIFE SHARPENER - field, home or shop use designed for sportsmen who need a complete, compact field sharpening solution. The diamond plates can be easily removed to expose a broad head wrench to speed sharpening in the field. Diamond plates can be attached with the abrasive exposed or flipped over during transport in your gear bag. DIAMOND PLATES, CERAMIC RODS, LEATHER STROP, & SHARPENING GUIDES - provide a fast, easy & consistent sharpening solution for knives & camp tools. The ceramic honing rod rotates to expose coarse & fine honing surfaces, as well as a grooved surface for sharpening fish hooks. A second, small ceramic rod is used for sharpening serrations. CONSISTENT BLADE EDGE ANGLES - purpose built 20° angle guide for sharpening with the diamond plates, & 25° angle guide for honing a strong micro-bevel. Five abrasive steps provide a complete sharpening solution: coarse & fine diamond sharpening plates, coarse & fine ceramic hones, & a leather strop. COMPACT & DURABLE - maintain your edge while out hunting, fishing, camping or anywhere you need a sharp edge. All elements are self-contained & require no tools, assembly, or set-up. PROUD TO BE AN AMERICAN COMPANY - This tool was engineered and assembled by hard working Americans. Work Sharp is part of Darex, a 4th-generation family owned company in Ashland, Oregon. For over 40 years we have been creating industry-leading sharpening tools here in the USA.', 24.90, 5, 'https://images-na.ssl-images-amazon.com/images/I/71aqCgzM7WL._AC_SL1500_.jpg', DEFAULT, FALSE),
  (86, "Maple Cream Cookies", '18 cookies per box with creamy, delicious maple syrup filling. This item contains two boxes of 18 cookies, total 36 cookies.', 14.95, 6,"https://images-na.ssl-images-amazon.com/images/I/91YOuHIL%2BaL._SL1500_.jpg", DEFAULT, FALSE),
  (87, "Bannock", "A boring variety of flat quick bread. Bannock is best not eaten unless absolutely necessary. Satisfaction not guaranteed. No refunds.", 1.23, 6,"https://upload.wikimedia.org/wikipedia/commons/d/d2/BannockBeremeal.jpg", DEFAULT, FALSE),
  (88, "Fresh Polar Bear Meat", "Sustainably raised on a natural diet of narwhals and walruses, this polar bear meat is both good for the environment and tasty. Minimal prep required, though even the pickier eaters will love the meat when lightly roasted over an open flame.", 314159.26, 6,"https://e3.365dm.com/17/03/768x432/a80f632b627bc3fbd85292a03a92c26cbb951dcb063af2a307b5f17b39614378_3904835.jpg?20170307125405", DEFAULT, FALSE),
  (89, "Fiddleheads", "Freshly picked fiddlehead ferns from the wilds of Canada. Nutritious and delicious.", 14.23, 6,"https://i.etsystatic.com/17372702/r/il/f62edd/1508047481/il_794xN.1508047481_q4ta.jpg", DEFAULT, FALSE),
  (90, "Tim Horton's Maple Donut", "A delicious maple donut shipped directly to you from the Canadian icon, Tim Hortons.", 752.31, 6,"https://i0.wp.com/checkbeforeyoutrek.com/wp-content/uploads/2016/06/TH-Donut.jpg?w=1020&ssl=1", DEFAULT, FALSE),
  (91, "Wild Smoked Salmon Jerky", "Salmon jerky is an unparalleled Canadian delicacy. This wild-smoked salmon can be enjoyed as a snack or as a meal substitute, especially for breakfast!", 37.42, 6,"https://shop.r10s.jp/auc-canadian/cabinet/food/10salmonjerkey.jpg", DEFAULT, FALSE),
  (92, "Inniskillin Ice Wine Cabernet Franc, 2014", "Niagra, Ontario, Canada- Amazing depth of colour and outstanding red berry flavours, particularly strawberry, lend this red Icewine to pair well with chocolate or chocolate mousse and red fruit based desserts or simply strawberries and cream!", 100.00, 6,"https://www.totalwine.com/dynamic/1000x/media/sys_master/twmmedia/h36/ha0/8818913247262.png", DEFAULT, FALSE),
  (93, "Fresh Caribou Meat", "The freshest caribou meat possible! (Handle with care.)", 3000.00, 6,"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Caribou.jpg/1200px-Caribou.jpg", DEFAULT, FALSE),
  (94, "Monreal-Style Smoked Meat", "Montreal-style smoked meat is a type of kosher-style deli meat product made by salting and curing beef brisket with spices. The brisket is allowed to absorb the flavours over a week, is then hot smoked to cook through, and finally is steamed to completion.", 18.23, 6,"https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Schwartz_smoked_meat_montreal.JPG/1280px-Schwartz_smoked_meat_montreal.JPG", DEFAULT, FALSE),
  (95, "Montreal-Style Bagels", "Unlike their New York counter parts each bagel is boiled in honey water, and cooked in a wood fired oven that was designed to both cook and flavor the bagel. What comes out of  this process is a chewy, slightly sweet bagel that is incomparable to any other bagel around!", 23.50, 6,"https://s31833.pcdn.co/wp-content/uploads/2017/06/woodgrainBagels-bagels-600x381.jpg", DEFAULT, FALSE),
  (96, "Muktuk", "Muktuk is the traditional Inuit and Chukchi meal of frozen whale skin and blubber.", 327.84, 6,"https://alchetron.com/cdn/muktuk-cdca7f38-c0f7-4066-8fef-ad38e02c210.jpeg", DEFAULT, FALSE),
  (97, "Tourtière", "Seasoned pork, beef, and veal in a pastry shell. Simply bake and serve.", 5.00, 6,"https://assets.shop.loblaws.ca/products_jpeg/20153080/en/20153080_lrg_1_@1x.jpg", DEFAULT, FALSE),
  (98, "Nanaimo Bars", "Nanaimo bars have a crumb base, custard filling, and chocolate topping. This layered Canadian dessert can be flavoured with mint or coconut and is best served on its own at room temperature.", 7.00, 6,"https://i5.walmartimages.ca/images/Enlarge/508/574/6000198508574.jpg", DEFAULT, FALSE),
  (99, "Butter Tarts", "Butter tarts are iconic Canadian desserts. Recipes vary across the country and everyone has an opinion on what makes the best butter tart. Typically they have a crisp pastry and a soft filling made of butter, sugar, syrup, and raisins or nuts. Butter tarts vary in size but can usually be enjoyed in one or two delicious bites.", 5.99, 6,"https://assets.shop.loblaws.ca/products_jpeg/21070344/en/21070344_lrg_1_@1x.jpg", DEFAULT, FALSE),
  (100, "Peameal Bacon", 'Back bacon is a traditional British style of round, lean bacon cut from the pork loin. Canadian bacon, or peameal bacon, is back bacon rolled in cornmeal.', 8.49, 6,"https://assets.shop.loblaws.ca/products_jpeg/20133609/en/20133609_lrg_1_@1x.jpg", DEFAULT, FALSE),
  (101, "Ketchup Flavour Chips", "One Large Bag Authentic, Delicious, and Fresh Ketchup Chips imported from Canada and delivered to your door! Quality and Freshness guaranteed. Expiration date clearly labelled and guaranteed to be shipped with valid expiry date or your money back. Bold, and full of rich flavor Crunchy Snack time delight", 10.97, 6,"https://images-na.ssl-images-amazon.com/images/I/516JRvnx2RL.jpg", DEFAULT, FALSE),
  (102, "Poutine Gravy", "St Hubert Poutine Gravy mix is a delicious sauce which is used to make the famous Canadian dish Poutine.", 6.27, 6,'https://images-na.ssl-images-amazon.com/images/I/41PKB0cxLyL.jpg', DEFAULT, FALSE);


  -- select itemData.productId,itemData.productName,itemData.productDescription,itemData.price, categories.category from itemData inner join categories on itemData.categoryId=categories.categoryId;

  -- select images.imgUrl from images inner join itemData on images.productId=itemData.productId;

  -- select (select itemData.productId,itemData.productName,itemData.productDescription,itemData.price, categories.category from itemData inner join categories on itemData.categoryId=categories.categoryId,)

  -- select 
  --   itemData.productId,
  --   itemData.productName,
  --   itemData.productDescription,
  --   itemData.price, 
  --   categories.category,
  --   images.imgUrl
  -- from itemData limit 1
  -- inner join categories on itemData.categoryId=categories.categoryId 
  -- inner join images on images.productId=itemData.productId 
  -- where itemData.productId = 1;



